# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  
jobs:

  print_hello:
    docker:
     - image: circleci/node:13.8.0
    steps:
      - run: echo "Hello"
  # Job two with a unique name
  print_world:
    docker:
     - image: circleci/node:13.8.0
    steps:
      - run: echo "World"
  
  print_name:
    docker:
     - image: circleci/node:13.8.0
    steps:
      - run: echo $name


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  hello_and_goodbye:
    # List of jobs that will run
    jobs:
      - print_hello
      - print_name
      - print_world:
          requires:
            - print_hello
